import React from 'react'
import { BrandingProvider } from '@/contexts/BrandingContext'

import './index.scss'

const baseClass = 'multi-tenant'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
}

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={baseClass} lang="en">
      <body>
        <BrandingProvider>
          {children}
        </BrandingProvider>
      </body>
    </html>
  )
}
