[build]
  publish = ".next"
  command = "node netlify-build.js && powershell -Command \"$env:NEXT_PHASE='phase-production-build'; pnpm build\""

[build.environment]
  NODE_VERSION = "18"
  NPM_USE_PRODUCTION = "false"
  NEXT_PHASE = "phase-production-build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Handle Next.js rewrites and redirects
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers for PWA and security
[[headers]]
  for = "/api/manifest"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/api/pwa/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/api/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# PWA headers
[[headers]]
  for = "/"
  [headers.values]
    X-Robots-Tag = "index, follow"

# Environment-specific settings
[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"

# Form handling (if needed for contact forms)
[forms]
  settings = true
